### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by GarethWright** [frozeman/meteor-build-client#12]
Once copied onto my server routing works fine if you hit the root url first, but not if you hit a root/charts

404 error.

Any way to get this working again?

**Comment by Type1J** [comment]
Links might solve your problem, but you'll have to make them for every path that you might have.
    cd charts
    ln ../index.html index.html
if you do a symlink:
    cd charts
    ln -s ../index.html index.html
then some websevers will not follow it because they see it as a security issue.

Note that when you edit index.html in one place, they all change, but they *look* like separate files; they don't show as symlinks when you ls the directory.

**Comment by GarethWright** [comment]
I ended up just using htaccess at rewrite urls back to index.html.

**Comment by Type1J** [comment]
@GarethWright That's a much better way of handling it. I thought of that just a few minutes ago, but you beat me to it.

**Comment by GeoffreyBooth** [comment]
Something like this should probably be added to the docs. For Apache, this can be your `.htaccess` file:

```bash
<IfModule mod_rewrite.c>
	RewriteEngine On
	RewriteBase /

	# Always pass through requests for files that exist
	# Per http://stackoverflow.com/a/7090026/223225
	RewriteCond %{REQUEST_FILENAME} -f [OR]
	RewriteCond %{REQUEST_FILENAME} -d
	RewriteRule . - [L]

	# Send all other requests to index.html where the JavaScript router can take over
	# and render the requested route
	RewriteRule ^.*$ index.html [L]
</IfModule>

**Comment by frozeman** [comment]
Will add.
