### ISSUE TITLE
repost from meteor #6061: meteor build filenames 

### ISSUE THREAD

**Issue by brettg2** [frozeman/meteor-build-client#23]
I am using git to track the output of `meteor-build-client` but the scripts and styles are changing file names each time the process runs. This means git thinks the prior version of the scripts are being deleted and the new files are being created / added. 

Example:

```
02fa888b4b14f641de5add8c54923fefdb85c36f.js
737d4405b6d5123d24bbc1339055c0800a7406b4.css
index.html
```

... changing to:

```
05e746150274630cb5732dc013fbd08c7d262996.js
5cd04d43a893cab1c2c43355b3265eca8b063f94.css
index.html
```

(Git sees this as deleting the first files and adding the new, which means redundant data is being stored in the git repository)

Is there a way to use a common file name each time the build process is run instead of using a generated hash string? 

Thank you.

**Comment by frozeman** [comment]
These file names are generated by the meteor build process and the point is that the hash represents the content. This helps if you want to prevent coaching of these resources for example.

If you want to add the feature to give them custom file names, you can probably come up with a PR, where you specify some option like `--filenames "myFile"` and it renames the files to:
```js
myFile.js
myFile.css
index.html
```

**Comment by dr-dimitru** [comment]
I believe adding a feature for file naming isn't necessary as submitting a build to GIT almost on every project generates enormous diffs, that's okay.

And everything is automated — those generated hash-file-names are added to <head> of generated `index.html`. 

Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
