### ISSUE TITLE
How to connect build client to server ?

### ISSUE THREAD

**Issue by Furqankhanzada** [frozeman/meteor-build-client#6]
I am building Chrome App and this module is perfect for it but question after building client how can i connect it back to the server.

I saw that you have provided an example :

``` js
DDPConnection = (Meteor.isClient) ? DDP.connect('http://localhost:3000/') : {};

if(Meteor.isClient) {
    // set the new DDP connection to all internal packages, which require one
    Meteor.connection = DDPConnection;
    Accounts.connection = Meteor.connection;
    Meteor.users = new Mongo.Collection('users');
    Meteor.connection.subscribe('users');
}

// When creating a collection use:
posts = new Mongo.Collection("posts", DDPConnection);
// And to subscribe use the DDP connection
DDPConnection.subscribe("mySubscription");
```

Question is where i need to place this ? can you show an example ?

**Comment by Furqankhanzada** [comment]
@frozeman : any help ?

**Comment by frozeman** [comment]
Should be in both server and client in a lib folder
```js
DDPConnection = (Meteor.isClient) ? DDP.connect('http://localhost:3000/') : {};

// When creating a collection use:
posts = new Mongo.Collection("posts", DDPConnection);
```

In the client
```js
if(Meteor.isClient) {
    // set the new DDP connection to all internal packages, which require one
    Meteor.connection = DDPConnection;
    Accounts.connection = Meteor.connection;
    Meteor.users = new Mongo.Collection('users');
    Meteor.connection.subscribe('users');
}
```

And then you subscribe like this:
```js
// And to subscribe use the DDP connection
DDPConnection.subscribe("mySubscription");
```

**Comment by duffar** [comment]
@frozeman 
If the client files generated by your tool are being served up from the same web server hosting the DDP backend is it possible to use the implicit DDP connect (i.e. convenience) method rather than the explicit DDP.connect method described in your docs?

I'm creating a DDP server in python and I'm using your tool to bundle the front end app. My python server can serve the app and it connects back to the DDP websocket hosted by the same server. This all works fine when I use the explicit DDP.connect mechanism but it doesn't work if I use the default mechanism of connecting back to the host that served the app. Oddly I can see the sockjs/info call but I never get the websocket connection.

I'm not sure what triggers the actual web socket connection and why its not occurring.

Does this get any easier in Meteor 1.2?

-Jeff

P.S. Thanks for your package... it's been helpful getting me up and running

**Comment by frozeman** [comment]
Sadly i don't know the internals of `Meteor.connect`, but i would assume that it has a slightly different url like `ddp.myseite.com` or so. 

I'm happy that you like my package

**Comment by duffar** [comment]
Indeed... I finally realized that I didn't have ROOT_URL defined at all when running the build so it came through as empty in the generated index.html runtime config settings. Once I defined that implicit connections worked fine. This explains why the explicit connections worked as I was programmatically telling meteor where to connect in that case. Thanks again.

**Comment by duffar** [comment]
I also found that by removing the ROOT_URL setting completely from the meteor_runtime_config that meteor does default back to the host that served the file. It was the fact that I had ROOT_URL set to an empty string that was tripping it up.

**Comment by frozeman** [comment]
The ROOT_URL is set using the `--url` option. Do you think it would be better to no set it at all, as default?

**Comment by duffar** [comment]
Yeah I think that would be great. Then meteor would connect back to the serving host by default. Which sounds right to me.

**Comment by frozeman** [comment]
Hm, actually i'm not sure, as currently i anyway add `Meteor.disconnect()` as a default. 

The idea is that meteor build client is mainly used by people not using a standard Meteor server and so preventing the default connection is actually intended.

For my projects i use Meteor in electron as pure desktop apps. They don't connect to anywhere. 

I think the `--url` is actually fine as is. Though i will put a bit more thinking in it.

**Comment by duffar** [comment]
Hmmm... that is actually my use case as well because my server is definitely not a standard Meteor server ;) 

The implicit DDP connect is important to me because my client UI uses angular over meteor and the angular wrappers do not currently let you specify a specific connection when subscribing to a collection. They only work with the default connection - as far as I can tell. 

I'm not familiar with electron but it sounds interesting. If the auto-connect behavior would cause trouble there perhaps you could have a special build flag to enable/disable the auto-connect? or maybe specify a special value to the current flag (i.e. --url None)

If you'd like I can help with a PR... just want to make sure I'm not doing anything that would disrupt your electron environment.

**Comment by frozeman** [comment]
I could add `--url "default"` or so.

**Comment by frozeman** [comment]
ok I made this change in 0.1.8

**Comment by frozeman** [comment]
Please test an let me know

**Comment by duffar** [comment]
awesome... Thank you! The branch isn't showing up on github yet but I'll keep checking

**Comment by duffar** [comment]
I'm still not seeing it. Did you push your branch to github? All I see there is master. Or is there somewhere else I should be looking?

**Comment by frozeman** [comment]
ah sorry, i just updated npm, will push

**Comment by duffar** [comment]
Works perfectly. Thanks again Fabian!

**Comment by juliomac** [comment]
Dear @frozeman  and @Furqankhanzada , what are your thoughts about using Meteor_build_client to build Widgets/Plugins insertable on static HTML pages? 

Would that be a good approach?

It would be using standard meteor server.

**Comment by frozeman** [comment]
I don't think so, as you would load the whole meteor components, which is around 400kb. This just for a widget sounds a little much

**Comment by juliomac** [comment]
Thanks! And also add the packages, midia/pictures... Mine is reaching 4.4MB. But the other option would be rewriting the front end and adding bootstrap, Blaze, Jquery... all manually. The problem in this isomorphic world would be the other packages with both server and client side code. Here I'm lost...

How does ```Meteor_build_client``` deals with Isomorphic packages? Could some of this 400kb still be reduced?

**Comment by frozeman** [comment]
The server side is not packaged. Only the frontend code

**Comment by dr-dimitru** [comment]
This issue is archived.
Feel free to reopen it in case if the issue is still persists on your end.
